### PR TITLE
Message_t.len needs to be 16 bits, not 8

### PR DESCRIPTION
**Pull request by brandonros**

### CODE REVIEW

**Comment by brandonros** [comment]
```
01:07:32.022 -> ISO-TP State: 1
01:07:32.022 -> Length      : 4095
01:07:32.068 -> Send FF
01:07:32.068 -> Send CAN RAW Data:
01:07:32.068 -> Buffer: 7E5 [8] 1F FF 36 01 FF FF FF FF 
01:07:32.068 -> ISO-TP State: 4
01:07:32.068 -> Length      : 4089
01:07:32.068 -> Wait first FC
01:07:32.068 -> Received CAN RAW Data:
01:07:32.068 -> Buffer: 7ED [8] 30 20 00 55 55 55 55 55 
01:07:32.068 -> Send branch:
01:07:32.068 -> FC frame: FS 0, Blocksize 32, Min. separation Time 0
01:07:32.068 -> rxId OK!
01:07:32.068 -> ISO-TP State: 3
01:07:32.068 -> Length      : 4089
01:07:32.068 -> Send CF
01:07:32.068 -> Send CAN RAW Data:
01:07:32.068 -> Buffer: 7E5 [8] 21 FF FF FF FF FF FF FF 
01:07:32.068 -> Send Seq 1
01:07:32.068 -> Blocksize trigger 1 no
01:07:32.068 -> Length      : 4082
01:07:32.068 -> Send CAN RAW Data:
01:07:32.068 -> Buffer: 7E5 [8] 22 FF FF FF FF FF FF FF 
01:07:32.068 -> Send Seq 2
01:07:32.068 -> Blocksize trigger 2 no
01:07:32.068 -> Length      : 4075
01:07:32.115 -> Send CAN RAW Data:
01:07:32.115 -> Buffer: 7E5 [8] 23 FF FF FF FF FF FF FF 
01:07:32.115 -> Send Seq 3
01:07:32.115 -> Blocksize trigger 3 no
01:07:32.115 -> Length      : 4068
01:07:32.115 -> Send CAN RAW Data:
01:07:32.115 -> Buffer: 7E5 [8] 24 FF FF FF FF FF FF FF 
01:07:32.115 -> Send Seq 4
01:07:32.115 -> Blocksize trigger 4 no
01:07:32.115 -> Length      : 4061
01:07:32.115 -> Send CAN RAW Data:
01:07:32.115 -> Buffer: 7E5 [8] 25 FF FF FF FF FF FF FF 
01:07:32.115 -> Send Seq 5
01:07:32.115 -> Blocksize trigger 5 no
01:07:32.115 -> Length      : 4054
01:07:32.115 -> Send CAN RAW Data:
01:07:32.115 -> Buffer: 7E5 [8] 26 FF FF FF FF FF FF FF 
01:07:32.115 -> Send Seq 6
01:07:32.115 -> Blocksize trigger 6 no
01:07:32.115 -> Length      : 4047
01:07:32.115 -> Send CAN RAW Data:
01:07:32.115 -> Buffer: 7E5 [8] 27 FF FF FF FF FF FF FF 
01:07:32.163 -> Send Seq 7
01:07:32.163 -> Blocksize trigger 7 no
01:07:32.163 -> Length      : 4040
01:07:32.163 -> Send CAN RAW Data:
01:07:32.163 -> Buffer: 7E5 [8] 28 FF FF FF FF FF FF FF 
01:07:32.163 -> Send Seq 8
01:07:32.163 -> Blocksize trigger 8 no
01:07:32.163 -> Length      : 4033
01:07:32.163 -> Send CAN RAW Data:
01:07:32.163 -> Buffer: 7E5 [8] 29 FF FF FF FF FF FF FF 
01:07:32.163 -> Send Seq 9
01:07:32.163 -> Blocksize trigger 9 no
01:07:32.163 -> Length      : 4026
01:07:32.163 -> Send CAN RAW Data:
01:07:32.163 -> Buffer: 7E5 [8] 2A FF FF FF FF FF FF FF 
01:07:32.163 -> Send Seq 10
01:07:32.163 -> Blocksize trigger 10 no
01:07:32.163 -> Length      : 4019
01:07:32.163 -> Send CAN RAW Data:
01:07:32.163 -> Buffer: 7E5 [8] 2B FF FF FF FF FF FF FF 
01:07:32.163 -> Send Seq 11
01:07:32.163 -> Blocksize trigger 11 no
01:07:32.163 -> Length      : 4012
01:07:32.163 -> Send CAN RAW Data:
01:07:32.163 -> Buffer: 7E5 [8] 2C FF FF FF FF FF FF FF 
01:07:32.211 -> Send Seq 12
01:07:32.211 -> Blocksize trigger 12 no
01:07:32.211 -> Length      : 4005
01:07:32.211 -> Send CAN RAW Data:
01:07:32.211 -> Buffer: 7E5 [8] 2D FF FF FF FF FF FF FF 
01:07:32.211 -> Send Seq 13
01:07:32.211 -> Blocksize trigger 13 no
01:07:32.211 -> Length      : 3998
01:07:32.211 -> Send CAN RAW Data:
01:07:32.211 -> Buffer: 7E5 [8] 2E FF FF FF FF FF FF FF 
01:07:32.211 -> Send Seq 14
01:07:32.211 -> Blocksize trigger 14 no
01:07:32.211 -> Length      : 3991
01:07:32.211 -> Send CAN RAW Data:
01:07:32.211 -> Buffer: 7E5 [8] 2F FF FF FF FF FF FF FF 
01:07:32.211 -> Send Seq 15
01:07:32.211 -> Blocksize trigger 15 no
01:07:32.211 -> Length      : 3984
01:07:32.211 -> Send CAN RAW Data:
01:07:32.211 -> Buffer: 7E5 [8] 20 FF FF FF FF FF FF FF 
01:07:32.211 -> Send Seq 0
01:07:32.211 -> Blocksize trigger 0 yes
01:07:32.260 -> Length      : 3977
01:07:32.260 -> ISO-TP State: 5
01:07:32.260 -> Length      : 3977
01:07:32.260 -> Wait FC
01:07:32.260 -> ISO-TP State: 5
01:07:32.260 -> Length      : 3977
01:07:32.260 -> Wait FC
01:07:32.260 -> ISO-TP State: 5
01:07:32.260 -> Length      : 3977
01:07:32.260 -> Wait FC
```

this isn't related to the pull request but I can't make an issue. I get an infinite loop here when I know for a fact the device (a real engine control unit that is very modern that I have flashed 100 times+) is sending the flow control frame. What do you recommend?

**Comment by brandonros** [comment]
The closer I look at the logic, it looks like you never tested this with `blocksize = 0x20`?

**Comment by collin80** [comment]
Yes, I did next to nothing to this library - merely porting the existing library over so it would work with my can_common drivers. Then I really didn't ever do much with this ISO-TP library. I've fixed the problem where "Issues" wasn't enabled for this repo. I have no idea why it was off. And, I'll go ahead and merge these changes. Thanks.

**Comment by brandonros** [comment]
I have a weird issue now where sending large frames (4095 bytes) only works if ISOTP_DEBUG is off. Any tips?

**Comment by collin80** [comment]
Well, if it works when ISOTP_DEBUG is on then the probable cause is that debugging info causes extra delays. Why does it require these extra delays? I can't say for sure. I wish I had ever really done much with the library. I certainly have never tried to send 4095 byte frames with it. So, you're in uncharted territory. You might try commenting out the #ifdef ISOTP_DEBUG sections one by one to try to find which one is causing the needed delay. I know that's a tedious process but I otherwise am not really sure where the delay is needed to help things work better.

**Pull request merged**
